cache:
  mount:
    - .git
    - vendor

build:
  image: golang
  environment:
    - GO15VENDOREXPERIMENT=1
  volumes:
    # dockerAPI
    - /var/run/docker.sock:/var/rundocker.sock
    # getHexPorts
    - /proc/net/tcp:/proc/net/tcp
    - /proc/net/udp:/proc/net/udp
  commands:
    # filesystem
    - ln -sT / /fakeroot
    - echo 'This is a file to check the "checksum" check.' > /tmp/test.txt
    - chmod 0644 /tmp/test.txt
    # Get packages that distributive tests
    - apt-get update > /dev/null
    - apt-get install -y sudo > /dev/null       # docker
    - apt-get install -y net-tools > /dev/null  # network
    - apt-get install -y lm-sensors php5-cli module-init-tools > /dev/null # misc
    # TODO: make all tests work in drone!  Missing: checklists, checks, memstatus, netstatus
    - go get github.com/Masterminds/glide
    - glide install
    - go test . ./chkutil ./dockerstatus ./errutil ./fsstatus ./netstatus ./systemdstatus ./tabular
    - go install .
    - distributive --verbosity=info -d "./samples"
